// <auto-generated />
using FilmDirectorsApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FilmDirectorsApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260621225751_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FilmDirectorsApi.Models.Director", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Directors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Christopher Nolan",
                            Nationality = "British"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Martin Scorsese",
                            Nationality = "American"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Quentin Tarantino",
                            Nationality = "American"
                        });
                });

            modelBuilder.Entity("FilmDirectorsApi.Models.Film", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DirectorId")
                        .HasColumnType("int");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TmdbId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DirectorId");

                    b.ToTable("Films");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DirectorId = 1,
                            ReleaseYear = 2010,
                            Title = "Inception",
                            TmdbId = 27205
                        },
                        new
                        {
                            Id = 2,
                            DirectorId = 1,
                            ReleaseYear = 2008,
                            Title = "The Dark Knight",
                            TmdbId = 155
                        },
                        new
                        {
                            Id = 3,
                            DirectorId = 2,
                            ReleaseYear = 1990,
                            Title = "Goodfellas",
                            TmdbId = 769
                        },
                        new
                        {
                            Id = 4,
                            DirectorId = 2,
                            ReleaseYear = 2006,
                            Title = "The Departed",
                            TmdbId = 1422
                        },
                        new
                        {
                            Id = 5,
                            DirectorId = 3,
                            ReleaseYear = 1994,
                            Title = "Pulp Fiction",
                            TmdbId = 680
                        },
                        new
                        {
                            Id = 6,
                            DirectorId = 3,
                            ReleaseYear = 2012,
                            Title = "Django Unchained",
                            TmdbId = 68718
                        });
                });

            modelBuilder.Entity("FilmDirectorsApi.Models.Film", b =>
                {
                    b.HasOne("FilmDirectorsApi.Models.Director", "Director")
                        .WithMany("Films")
                        .HasForeignKey("DirectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Director");
                });

            modelBuilder.Entity("FilmDirectorsApi.Models.Director", b =>
                {
                    b.Navigation("Films");
                });
#pragma warning restore 612, 618
        }
    }
}
