// <auto-generated />
using FilmDirectorsApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FilmDirectorsApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260621234208_AddTmdbPersonId")]
    partial class AddTmdbPersonId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FilmDirectorsApi.Models.Director", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TmdbPersonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Directors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Christopher Nolan",
                            Nationality = "British",
                            TmdbPersonId = 525
                        },
                        new
                        {
                            Id = 2,
                            Name = "Martin Scorsese",
                            Nationality = "American",
                            TmdbPersonId = 1032
                        },
                        new
                        {
                            Id = 3,
                            Name = "Quentin Tarantino",
                            Nationality = "American",
                            TmdbPersonId = 138
                        },
                        new
                        {
                            Id = 4,
                            Name = "Stanley Kubrick",
                            Nationality = "American",
                            TmdbPersonId = 240
                        },
                        new
                        {
                            Id = 5,
                            Name = "Steven Spielberg",
                            Nationality = "American",
                            TmdbPersonId = 488
                        },
                        new
                        {
                            Id = 6,
                            Name = "David Fincher",
                            Nationality = "American",
                            TmdbPersonId = 7467
                        },
                        new
                        {
                            Id = 7,
                            Name = "Alfred Hitchcock",
                            Nationality = "British",
                            TmdbPersonId = 2636
                        },
                        new
                        {
                            Id = 8,
                            Name = "Ridley Scott",
                            Nationality = "British",
                            TmdbPersonId = 578
                        });
                });

            modelBuilder.Entity("FilmDirectorsApi.Models.Film", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DirectorId")
                        .HasColumnType("int");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TmdbId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DirectorId");

                    b.ToTable("Films");
                });

            modelBuilder.Entity("FilmDirectorsApi.Models.Film", b =>
                {
                    b.HasOne("FilmDirectorsApi.Models.Director", "Director")
                        .WithMany("Films")
                        .HasForeignKey("DirectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Director");
                });

            modelBuilder.Entity("FilmDirectorsApi.Models.Director", b =>
                {
                    b.Navigation("Films");
                });
#pragma warning restore 612, 618
        }
    }
}
